@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface ItemClickListener

ScooterSharingActivity *--- ScooterSharingFragment
ScooterSharingActivity *--- ActiveRideFragment
ScooterSharingActivity *--- MapsFragment
ScooterSharingActivity *--- PaymentFragment
ScooterSharingActivity *--- ScooterArrayAdapter
ScooterArrayAdapter<-- RideHistoryFragment
ScooterSharingVM <|- ScooterSharingActivity
ScooterSharingVM <|-- LocationFragment
RideHistoryFragment <|-- Rides



class ActiveRideFragment {
Object[] elementData
size()
}

class MapsFragment {
Object[] elementData
size()
}

class PaymentFragment {
Object[] elementData
size()
}

class ReceiptFragment{
Object[] elementData
size()
}

class RideHistoryFragment {
Object[] elementData
size()
}

class ScooterSharingFragment{
Object[] elementData
size()
}

class ScooterArrayAdapter {
Object[] elementData
size()
}

class ScooterSharingActivity {
Object[] elementData
size()
}

class LoginActivity {
Object[] elementData
size()
}

class MyApplication {
Object[] elementData
size()
}

class Rides {
Object[] elementData
size()
}

class RidesListViewModel {
Object[] elementData
size()
}

class Scooter {
Object[] elementData
size()
}

class ScooterSharingVM {
Object[] elementData
size()
}

class ScooterService {
Object[] elementData
size()
}


@enduml